env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
rules:
  brace-style:
    - warn
    - 1tbs
  camelcase: warn
  comma-dangle:
    - warn
    - always-multiline
  comma-style:
    - error
    - last
  complexity:
    - error
    - 10
  curly: warn
  eol-last:
    - error
    - always
  id-length:
    - warn
    - exceptions:
        - t
  max-lines: warn
  max-params:
    - warn
    - 4
  no-duplicate-imports: error
  no-eq-null: error
  eqeqeq:
    - error
    - smart
  no-eval: error
  no-implied-eval: error
  no-invalid-this: error
  no-shadow: off
  "@typescript-eslint/no-shadow": error
  no-undefined: error
  no-empty-function: warn
  "@typescript-eslint/no-empty-interface": off
  no-extend-native: error
  no-param-reassign: warn
  no-unused-expressions: warn
  no-useless-concat: warn
  no-label-var: warn
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define": error
  no-const-assign: error
  no-useless-constructor: warn
  no-useless-rename: warn
  no-warning-comments:
    - warn
    - location: anywhere
      terms:
        - todo
        - fixme
  prefer-promise-reject-errors: error
  semi:
    - warn
    - always
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
