PUBLIC_URL: '/'
API_URL: 'http://localhost:4001/graphql'
#API_URL: 'https://7dvnzdnsujbvhly7e64qqy6i54.appsync-api.us-east-1.amazonaws.com/graphql'
version: '@dev'
HOSTED_UI_DOMAIN: 'biohazard-staging.auth.us-east-1.amazoncognito.com'
USER_POOL_ID: 'us-east-1_ifEOrHfGw'
USER_POOL_WEB_CLIENT_ID: '25gf855pvaouce5brmisnrfsr'
